<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'adherent_service' shared autowired service.

include_once $this->targetDirs[3].'\\src\\AppBundle\\Service\\AdherentService.php';

return $this->services['adherent_service'] = new \AppBundle\Service\AdherentService();
