<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNiwvdj4\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNiwvdj4/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNiwvdj4.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNiwvdj4\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNiwvdj4\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Niwvdj4',
    'container.build_id' => '2cf00be3',
    'container.build_time' => 1532274232,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNiwvdj4');
